import React, { useState } from "react";

const AuthenticatorAppCodeInput = ({ fullName, onSubmit }) => {
  const [code, setCode] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    onSubmit(code);
  };

  return (
    <div className="authenticator-app-code-input">
      <header className="authentication-app-heading">
        <h2>{fullName} • NamasteApp</h2>
        <h3>Get your code from your authentication app</h3>
        <p>Enter the 6-digit code generated by your authentication app.</p>
      </header>

      <form onSubmit={handleSubmit}>
        <label htmlFor="code">Enter code</label>
        <input
          type="text"
          id="code"
          value={code}
          onChange={(e) => setCode(e.target.value)}
          maxLength={6}
          required
        />
        <button type="submit" className="next-btn">Next</button>
      </form>
    </div>
  );
};

export default AuthenticatorAppCodeInput;
