import React, { useState } from "react";
import "../../styles/AuthenticatorAppCodeInput.css";
import authService from "../../service/AuthService";
import { toast } from "react-toastify";

const AuthenticatorAppCodeInput = ({ data, userId }) => {
  const [code, setCode] = useState("");

  const handleTfa = async (event) => {
    event.preventDefault();
    const tfaResponse = await authService.tfaVerification({
      userId: userId,
      code: code,
      password: data.password,
    });
    if (!tfaResponse.success) {
      toast.error("Failed to two factor authentication");
      return;
    }
    toast.info("Two Factor Authentication(2FA) is ON");
    
  };

  return (
    <div className="authenticator-app-code-input">
      <header className="authentication-app-code-heading">
        <h5>{data.firstname + " " + data.lastname} • NamasteApp</h5>
        <h2>Get your code from your authentication app</h2>
        <p>Enter the 6-digit code generated by your authentication app.</p>
      </header>

      <form className="tfa-form">
        <label htmlFor="code" className="tfa-label">
          Enter code
        </label>
        <input
          type="text"
          id="code"
          value={code}
          onChange={(e) => setCode(e.target.value)}
          maxLength={6}
          required
          className="tfa-input"
        />
        <button type="button" className="next-btn" onClick={handleTfa}>
          Next
        </button>
      </form>
    </div>
  );
};

export default AuthenticatorAppCodeInput;
