spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/namesteapp_db
    username: postgres
    password: postgres-password
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 60000
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: namasteapp.com
    password: namasteapp-password
    properties:
      smtp:
        trust: "*"
      auth: true
      starttls:
        enable: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000

springdoc:
  default-consumes-media-type: application/json

application:
  security:
    jwt:
      expiration: 259200000
      secret-key: dEHmGxg1Pd1xvTNdD2UBLQpYhc4FncMG5D-6qmTY6re0ZVgdPF4RN1xN9NEm5NtE0VWkbafCNdRJTN0FWbVDcg==
  file:
    uploads:
      media-output-path: ./uploads
      avtar-output-path: ./avtar