spring:
  application:
    name: namasteapp
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

#logging:
#  level:
#    com:
#      aniketkadam:
#        namaste_app: trace
