spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 60000
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma:2b
          temperature: 0.7

  mail:
    host: ${MAIL_HOST}
    port: 1025
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      smtp:
        trust: "*"
      auth: true
      starttls:
        enable: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLINET_SECRET}

springdoc:
  default-consumes-media-type: application/json

application:
  security:
    jwt:
      expiration: 259200000
      secret-key: ${SERVER_SECRET}
    AES:
      secret-key: ${AES_SECRET_KEY}

  file:
    uploads:
      media-output-path: ${FILE_UPLOAD_LOCATION}
      avtar-output-path: ${AVTAR_UPLOAD_LOCATION}
      status-output-path: ${STATUS_UPLOAD_LOCATION}
