name: Build & Deploy NamasteApp backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy NamasteApp backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Run unit test
        run: mvn -B test --file pom.xml

      - name: Build the backend
        run: |
          mvn clean
          mvn -B package --file pom.xml